remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
- jekyll-seo-tag

title: [LeetCode Solutions - Samir Paul]
description: [LeetCode Solutions in Python and C++]

show_downloads: ["true" or "false" (unquoted) to indicate whether to provide a download URL]
google_analytics: [G-CP4QE6ZEV0]

